services:
  push-server:
    image: qingzhoudev/push-server:latest
    container_name: push-server
    ports:
      - "8000:8000"
    volumes:
      - /home/xa/wechat-push/data:/app/data
    restart: unless-stopped